### ISSUE TITLE
website_sale_checkout_store

### ISSUE THREAD

**Issue by ideenweberei** [it-projects-llc/website-addons#186]
Portal Users get a 403 when trying to checkout shop/checkout?buyMethod=nobill_noship in odoo 10 version. Please fix urgently as we actually bought the module and it is useless at the moment!

**Comment by ideenweberei** [comment]
please also check attached screenshot.
![checkoutfailure](https://cloud.githubusercontent.com/assets/29098205/26668357/ab3a141e-46a9-11e7-816d-8cc0983381eb.PNG)

**Comment by yelizariev** [comment]
Thank you reporting. I've fixed this bug and we will fix another one related to public user soon (system shall not to show "Public user address")
![screenshot-06076-188-566288-base runbot it-projects info 2017-06-05 00-04-03](https://cloud.githubusercontent.com/assets/186131/26764590/dbf3d302-4982-11e7-8517-e112a39ed0d6.png)
