### ISSUE TITLE
Web Login Background

### ISSUE THREAD

**Issue by ilmir-k** [it-projects-llc/website-addons#25]
Для картинок использующих URL модуль web login background не работает.

**Comment by ilmir-k** [comment]
@iledarn

**Comment by ilmir-k** [comment]
@yelizariev As I remember it was in odoo 8.0

**Comment by trojikman** [comment]
Checked odoo versions from 10.0 to 12.0 - Web login background works well with URL on all versions

**Comment by yelizariev** [comment]
Can be closed then. We are not interested neither in 8 nor 9 versions
