### ISSUE TITLE
[8.0] oca_dependencies call bad python-chess version

### ISSUE THREAD

**Issue by carlosrve** [it-projects-llc/website-addons#389]
oca_dependencies.txt on v8.0 call for python-chess, with no version. But the latest version of python-chess will not install on python2. This is the pip output:
```
ImportError: You are installing python-chess on Python 2.
    
    Python 2 support has been dropped. Consider upgrading to Python 3, or using
    the 0.23.x branch, which will be maintained until the end of 2018.
```
I am doing a PR to fix this.

**Comment by yelizariev** [comment]
Fixed in 8 and 10 branches for now. We will merge 10 to 11, 11 to 12, so additional PR to 9 is required

**Comment by yelizariev** [comment]
9 version is not supported anymore. The rest is done
